# Lista estática dos 100 principais pares USDT negociados na KuCoin
SYMBOLS = [
    'BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'BNB/USDT', 'ADA/USDT', 'XRP/USDT', 'DOGE/USDT', 'TRX/USDT', 'LINK/USDT', 
    'LTC/USDT', 'DOT/USDT', 'BCH/USDT', 'SHIB/USDT', 'AVAX/USDT', 'OP/USDT', 'UNI/USDT', 'ATOM/USDT', 'ETC/USDT', 'XLM/USDT',
    'FIL/USDT', 'APT/USDT', 'SUI/USDT', 'HBAR/USDT', 'AR/USDT', 'INJ/USDT', 'VET/USDT', 'PEPE/USDT', 'NEAR/USDT',
    'GRT/USDT', 'CRO/USDT', 'STX/USDT', 'ALGO/USDT', 'QNT/USDT', 'IMX/USDT', 'WIF/USDT', 'TUSD/USDT', 'MINA/USDT',
    'DYDX/USDT', 'EGLD/USDT', 'AKT/USDT', 'TIA/USDT', 'JTO/USDT', 'MKR/USDT', 'AAVE/USDT', 'WBTC/USDT', 'PYTH/USDT', 'SAND/USDT',
    'CAKE/USDT', 'XMR/USDT', 'CHZ/USDT', 'BLUR/USDT', 'BTT/USDT', 'GMX/USDT', 'LDO/USDT', 'ENJ/USDT', 'FET/USDT', 'OSMO/USDT',
    'BICO/USDT', 'RPL/USDT', 'DYM/USDT', 'ZIL/USDT', 'SFP/USDT', 'SKL/USDT', '1INCH/USDT', 'GMT/USDT',
    'FLOW/USDT', 'CKB/USDT', 'XDC/USDT', 'XEC/USDT', 'SSV/USDT', 'ID/USDT', 'MEME/USDT', 'BOME/USDT',
    'BAND/USDT', 'BICO/USDT', 'LPT/USDT', 'SCRT/USDT', 'NKN/USDT', 'OGN/USDT', 'STORJ/USDT',
    'SUN/USDT', 'SXP/USDT', 'XNO/USDT', 'YGG/USDT', 'ZRX/USDT', 'RUNE/USDT', 'CELO/USDT'
]

# Timeframe padrão para análise
TIMEFRAME = '1d'
