SYMBOLS = [
    'BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'HYPE/USDT', 'PUMP/USDT', 'ENA/USDT', 'FARTCOIN/USDT', 'BONK/USDT', 'BNB/USDT', 'ADA/USDT', 'XRP/USDT', 'DOGE/USDT',
    'TRX/USDT', 'LINK/USDT', 'LTC/USDT','PENGU/USDT', 'DOT/USDT', 'BCH/USDT', 'SHIB/USDT', 'AVAX/USDT', 'OP/USDT', 'UNI/USDT', 'ATOM/USDT', 'ETC/USDT', 'XLM/USDT',
    'FIL/USDT', 'APT/USDT', 'SUI/USDT', 'HBAR/USDT', 'ZORA/USDT', 'AR/USDT', 'INJ/USDT', 'PEPE/USDT', 'NEAR/USDT', 'STX/USDT', 'ALGO/USDT', 'IMX/USDT', 'WIF/USDT',
    'MINA/USDT', 'DYDX/USDT', 'TIA/USDT', 'JTO/USDT', 'AAVE/USDT', 'PYTH/USDT', 'SAND/USDT', 'CAKE/USDT', 'XMR/USDT', 'BLUR/USDT', 'GMX/USDT', 'LDO/USDT', 'FET/USDT',
    'DYM/USDT', 'GMT/USDT', 'MEME/USDT', 'BOME/USDT', 'YGG/USDT', 'RUNE/USDT', 'CELO/USDT', 'WLD/USDT', 'ONDO/USDT', 'SEI/USDT', 'JUP/USDT', 'POPCAT/USDT', 'TAO/USDT',
    'TON/USDT'
]
TIMEFRAME = '15m'
